### ISSUE TITLE
Support for simple features

### ISSUE THREAD

**Issue by robsalasco** [PredictiveEcology/quickPlot#11]
Hi!

I'm really impressed with the speed of this package! I love it. Would be nice the support of Simple Features (https://github.com/r-spatial/sf) too additionally to the sp classes.

Great work!!

**Comment by eliotmcintire** [comment]
Thanks. Have started working on this, but hit a few snags about the sf classes not being exported in the standard ways...

**Comment by achubaty** [comment]
I believe `sf` objects are fully supported now. @eliotmcintire can we close this?

**Comment by eliotmcintire** [comment]
This is now supported in next release.
