### ISSUE TITLE
Visual unit tests using vdiffr package

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/quickPlot#21]
`expect_doppelganger` function

See CRAN version here:
[vdiffr](https://cran.rstudio.com/web/packages/vdiffr/index.html)

**Comment by achubaty** [comment]
see `testthat` snapshots: https://testthat.r-lib.org/articles/snapshotting.html

**Comment by eliotmcintire** [comment]
All visual tests have been converted to `testthat` snapshotting
