### ISSUE TITLE
Problem showing 1 specific layer in shiny app

### ISSUE THREAD

**Issue by luigidolcetti** [PredictiveEcology/quickPlot#24]
Hi,

I am trying to change base raster+sf plot in a shiny app to quickplot to see if performance improves. I found impossible to show a specific layer when specifying the layer name through a reactive input....
let's say 

Plot(rasterStack) -> shows all layers
Plot(rasterStack[[1]]) -> shows  first layer
Plot(rasterStack[[1]],title=input$whichLayer)-> specific layer with correct title
Plot(rasterStack[[input$whichLayer]])-> object 'input' not found (????), the same for other equivalents like $as.name(...)

Transforming rasterStack from a raster stack to a reactiveValues doesn't work, copying input$whichLayer to a static value gives the same error.... the only thing that works is:

specificLayer<-rasterStack[[input$whichLayer]] and then Plot(specificLayer).... but this obviously frustrates all the chance of getting better performances....

Any clues?

Thank you in advance,
Luigi

**Comment by luigidolcetti** [comment]
> 
> 
> Hi,
> 
> I am trying to change base raster+sf plot in a shiny app to quickplot to see if performance improves. I found impossible to show a specific layer when specifying the layer name through a reactive input....
> let's say
> 
> Plot(rasterStack) -> shows all layers
> Plot(rasterStack[[1]]) -> shows first layer
> Plot(rasterStack[[1]],title=input$whichLayer)-> specific layer with correct title
> Plot(rasterStack[[input$whichLayer]])-> object 'input' not found (????), the same for other equivalents like $as.name(...)
> 
> Transforming rasterStack from a raster stack to a reactiveValues doesn't work, copying input$whichLayer to a static value gives the same error.... the only thing that works is:
> 
> specificLayer<-rasterStack[[input$whichLayer]] and then Plot(specificLayer).... but this obviously frustrates all the chance of getting better performances....
> 
> Any clues?
> 
> Thank you in advance,
> Luigi

PS: obviously in a non-reactive context everything just work as expected

**Comment by eliotmcintire** [comment]
Hi @luigidolcetti ,
`Plot` looks in environments to find the objects that it is looking for. The R6 reference classes that are used throughout `shiny` (including the `input` object) won't work as you are hoping for `Plot` because they are "snuck" into the shiny app. There would have to be some work on our end to figure out how `shiny` is stashing its `inputs` R6 object. 

It looks like you haven't tried to assign the `inputs$whichLayer` to a new local object (which `Plot` can then find). Can you try that?

If that doesn't work, I am afraid that your only hope is your work around with a new local `RasterLayer`

**Comment by luigidolcetti** [comment]
Hi @eliotmcintire ,

thank you for your quick reply.
after a bit of trying with original lattice plot and some other derivations, I finally realised I was passing the data the wrong way.... anyway no luck at all since the retrieval of coordinates on_click then is completly messed up for everything but base plot.

Cheers,
Luigi

**Comment by eliotmcintire** [comment]
Ok. Good luck. Closing.
