### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [PredictiveEcology/quickPlot#25]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`quickPlot` imports 'rgdal', 'rgeos' and uses `rgeos::gArea` `rgeos::gIntersects` as found by `pkgapi`, bulk importing rgdal and properly importing `rgeos::gArea` `rgeos::gIntersects`; neither 'rgdal', 'rgeos' are needed by `raster`, which uses `terra`. Feasible replacements are `rgeos::gArea` may be `raster::area`, and  `rgeos::gIntersects`may be `terra::relate`. Please fix best by June, latest October 2023.

**Comment by eliotmcintire** [comment]
Thank you again. We are fully aware of this. We will work towards those dates.

**Comment by eliotmcintire** [comment]
This is finally complete. Just waiting for final tests, merge into main branches, and submission

**Comment by rsbivand** [comment]
Thanks, development branch looks good also tested with `_SP_EVOLUTION_STATUS_=2 _R_CHECK_SUGGESTS_ONLY_=true R CMD check`.

**Comment by eliotmcintire** [comment]
On CRAN now without `rgdal`, `rgeos` and/or `maptools` ... V 1.0.1
