### ISSUE TITLE
Plot() fails if there is a Plot() call already in the stack

### ISSUE THREAD

**Issue by ygc2l** [PredictiveEcology/quickPlot#9]
A reprex:

```
Plot <- function(x)
{
  quickPlot::Plot(x)
}

Plot(raster(matrix(1:100, 10, 10)))
```

I used the latest development branch (version is 0.1.2.9001).

**Comment by eliotmcintire** [comment]
Pushed a fix for this. I have added this reprex in the tests, so it is passing now.
